spring:
  application:
    name: target-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          audiences: http://localhost:9092/api/messages

server:
  port: 9092
logging:
  level:
    org.springframework.security: trace
